# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.1
group=dev.maksiks.amaranth
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Amaranth
mod_author=Lethargistic
mod_id=amaranth
license=ARR
credits=Lethargistic
description=A silly little biome mod.
minecraft_version_range=[1.21.1]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.116.9+1.21.1
fabric_loader_version=0.18.4

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.206
neoforge_loader_version_range=[5.10,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependency props
terrablender_version=4.1.0.8
terrablender_version_range=[4.1.0.8,)

twigonometry_version=0.1.1
twigonometry_version_range=[0.1.1,)

kff_version=5.10
kff_version_range=[5.10,)

flk_version=1.11.0+kotlin.2.0.0

fc_api_port_version=21.1.6

# Metadata
project_url=https://modrinth.com/mod/amaranth-biomes
project_color=0x8e26de
default_release_type=release

# Modrinth Metadata
modrinth_slug=amaranth-biomes
modrinth_id=Kvt7MP2Q
modrinth_game_versions=1.21.1

# CurseForge Metadata
curseforge_slug=amaranth-biomes
curseforge_id=1461639
