plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'org.jetbrains.kotlin.jvm'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    // amaranth
    implementation "com.github.glitchfiend:TerraBlender-neoforge:${minecraft_version}-${terrablender_version}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "maven.modrinth:twigonometry:mc${project.minecraft_version}-${project.twigonometry_version}-neoforge"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${fc_api_port_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(21)
}

